allowBuilds:
  core-js: false
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@posthog/core@1.55.0'
  - '@posthog/types@1.412.2'
  - posthog-js@1.434.2
  - '@posthog/browser-common@0.9.0'
